### ISSUE TITLE
pip3.exe error

### ISSUE THREAD

**Issue by zak-45** [bjia56/portable-python#113]
Hi, 

in process to test your portable version, I installed a win portable one, but when i want to use the pip3.exe command got this error:
```
C:\Users\zak-4\Desktop\python-full-3.10.14-windows-x86_64\python-full-3.10.14-windows-x86_64\Scripts>pip3.exe
Fatal error in launcher: Unable to create process using '"D:\a\portable-python\portable-python\build\python-install\bin\python.exe"  "C:\Users\zak-4\Desktop\python-full-3.10.14-windows-x86_64\python-full-3.10.14-windows-x86_64\Scripts\pip3.exe" ': Le fichier spÚcifiÚ est introuvable.
```

'specified file not found'

Had already set PATH env to take the portable python first, maybe miss some others....

Any way to be able to use pip to install some modules ?

Thanks

**Comment by bjia56** [comment]
The code that generates the executable likely needs to be patched to use a relative directory. I can look into it, in the meantime I recommend using pip as a module, e.g.
```
python -m pip install <package>
```
