### ISSUE TITLE
macOs issues with binaries

### ISSUE THREAD

**Issue by JavierRSobrino** [bjia56/portable-python#56]
This is what is installed on macOS arm64:

```
➜  bin git:(main) ✗ ls -la
total 856
drwxr-xr-x@ 8 javi  staff     256 15 may 17:11 .
drwxr-xr-x@ 8 javi  staff     256 15 may 17:40 ..
-rw-rw-rw-@ 1 javi  staff   70792  9 abr 08:09 libpython.py
-rw-rw-rw-@ 1 javi  staff     287  9 abr 20:31 pip3
-rw-rw-rw-@ 1 javi  staff     287  9 abr 20:31 pip3.12
-rwxrwxrwx@ 1 javi  staff  115960  9 abr 20:31 python
-rw-rw-rw-@ 1 javi  staff  115960  9 abr 20:31 python3
-rw-rw-rw-@ 1 javi  staff  115960  9 abr 20:31 python3.12

```
So you see there are 3 binaries repeated with the same name (they are not symlinks), but only one is executable (`python`). And the `pip3` files are not executable. Plus, pip3 doesn't have the proper path inside it:

```
➜  bin git:(main) ✗ cat pip3
#!/Users/runner/work/portable-python/portable-python/build/python-install/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from pip._internal.cli.main import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

Also, `pipx` is not installed.

**Comment by bjia56** [comment]
`adm-zip`, which is used by the nodejs-based installers, unfortunately does not handle symlinks very well. A change could be made to the installer to properly restore these symlinks and execute bits after extracting.

pip3 script can also be patched to look for the correct python interpreter, thanks for catching that. Previously pip has been launched only via a module and not through the script.

I am not familiar with pipx, what is your use case?

**Comment by JavierRSobrino** [comment]
`pipx`is for installing `poetry`, which would run a python service in the background.

**Comment by bjia56** [comment]
> `pipx`is for installing `poetry`, which would run a python service in the background.

Got it, thanks. I'm not convinced that pipx should be bundled with the portable Python distributions, since it isn't globally required and can be installed with `pip3 install pipx`.

**Comment by JavierRSobrino** [comment]
> > `pipx`is for installing `poetry`, which would run a python service in the background.
> 
> Got it, thanks. I'm not convinced that pipx should be bundled with the portable Python distributions, since it isn't globally required and can be installed with `pip3 install pipx`.

You are right, with pip3 we can install the rest.

**Comment by bjia56** [comment]
Should be fixed in the latest releases

**Comment by JavierRSobrino** [comment]
It is fixed, thank you.

But it happened what I suspected, I installed poetry, and this happened:

```
➜  bin git:(main) ✗ cat poetry 
#!/Users/javi/dev/bnn/node_modules/@bjia56/portable-python-3.12/python-3.12.3-darwin-universal2/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from poetry.console.application import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

```

I guess this is ok if it is used only for development, because my project will not change the path, but if I intend to distribute the application, I would need to change the paths manually everytime the app starts.
I wonder what would be the best approach to this. I intend to embed python into an electron app, so that app could really have any path, and the path can change from start to start (for example, if the user moves the app to another directory). What would be your recommendations?

**Comment by bjia56** [comment]
Hmm this might be difficult to patch from within portable python. What I would suggest is to have your Electron app get the path to the python interpreter with `PortablePython.executablePath`, then exec that and provide the path to `poetry` script as its arg1.

**Comment by bjia56** [comment]
Alternatively, maybe `<path to portable python> -m poetry` could work? That may be more cross-platform, since Windows installs python module scripts in a different path, and with a different format.

**Comment by JavierRSobrino** [comment]
> Alternatively, maybe `<path to portable python> -m poetry` could work? That may be more cross-platform, since Windows installs python module scripts in a different path, and with a different format.

This seems to work well. Thank you!
